// AUTO-GENERATED from the game XMLs (story.xml + per-chapter files + characters.xml).
// One entry per Season 1 chapter; each mission: code (missionEvent missionId),
// display name, main-boss villain and mission image (verified to exist client-side).
const S1_CHAPTERS = [
  { chapter: 1, name: 'The Pulse', missions: [
    { code: 's1c1m1', name: 'The Hydra\'s Tail', villain: 'VIPER', image: 'a/fs/31f0011.jpg' },
    { code: 's1c1m2', name: 'Class Is in Session', villain: 'WHIPLASH', image: 'a/fs/1ve0011.jpg' },
    { code: 's1c1m3', name: 'HAIL HYDRA!', villain: 'BARON ZEMO', image: 'a/fs/2hx0011.jpg' },
    { code: 's1c1m4', name: 'Designed Only for Killing', villain: 'M.O.D.O.K.', image: 'a/fs/wj0011.jpg' },
    { code: 's1c1m5', name: 'O Brother, Where Art Thou?', villain: 'LOKI', image: 'a/fs/iq0011.jpg' },
    { code: 's1c1m6', name: 'Extra Large', villain: 'ABOMINATION', image: 'a/fs/2gn0011.jpg' },
  ] },
  { chapter: 2, name: 'The Iso Effect', missions: [
    { code: 's1c2m1', name: 'In the Family', villain: 'HAMMERHEAD', image: 'a/fs/37u0011.jpg' },
    { code: 's1c2m2', name: 'The Sound of Feathers Ruffling', villain: 'VULTURE', image: 'a/fs/10k0011.jpg' },
    { code: 's1c2m3', name: 'Step into the Shadows', villain: 'BULLSEYE', image: 'a/fs/37n0011.jpg' },
    { code: 's1c2m4', name: 'Mean People', villain: 'THE HOOD', image: 'a/fs/2do0011.jpg' },
    { code: 's1c2m5', name: 'Mutate or Die', villain: 'MAGNETO', image: 'a/fs/1z90011.jpg' },
    { code: 's1c2m6', name: 'Ulterior Motive', villain: 'CRIMSON DYNAMO', image: 'a/fs/rf0011.jpg' },
  ] },
  { chapter: 3, name: 'Enter Doom', missions: [
    { code: 's1c3m1', name: 'Sacred Ground', villain: 'WHIPLASH', image: 'a/fs/1pw0011.jpg' },
    { code: 's1c3m2', name: 'Brooklyn Bridge is Falling Down', villain: 'HYDRO-MAN', image: 'a/fs/2xn0011.jpg' },
    { code: 's1c3m3', name: 'RAID-ical Resolutions', villain: 'FIXER', image: 'a/fs/2sm0011.jpg' },
    { code: 's1c3m4', name: 'Odd Bedfellows', villain: 'SABRETOOTH', image: 'a/fs/32l0011.jpg' },
    { code: 's1c3m5', name: 'Three Strikes', villain: 'GREEN GOBLIN', image: 'a/fs/3780011.jpg' },
    { code: 's1c3m6', name: 'Cephalocarrier', villain: 'DOCTOR OCTOPUS', image: 'a/fs/1100012.jpg' },
  ] },
  { chapter: 4, name: 'You, Foe', missions: [
    { code: 's1c4m1', name: 'Jailbreak', villain: 'IRONCLAD', image: 'a/fs/2u60011.jpg' },
    { code: 's1c4m2', name: 'Center Point', villain: 'VECTOR', image: 'a/fs/25x0011.jpg' },
    { code: 's1c4m3', name: 'Hydrophobia', villain: 'X-RAY', image: 'a/fs/3d0011.jpg' },
    { code: 's1c4m4', name: 'Unexpected Guest', villain: 'VAPOR', image: 'a/fs/2ij0011.jpg' },
    { code: 's1c4m5', name: 'Command Performance', villain: 'DR. DOOM', image: 'a/fs/1zr0011.jpg' },
    { code: 's1c4m6', name: 'Tooth and Claw', villain: 'SABRETOOTH', image: 'a/fs/zy0011.jpg' },
  ] },
  { chapter: 5, name: 'Gods & Monsters', missions: [
    { code: 's1c5m1', name: 'An Early Frost', villain: 'EXECUTIONER', image: 'a/fs/m80011.jpg' },
    { code: 's1c5m2', name: 'Taking AIM', villain: 'GREY GARGOYLE', image: 'a/fs/xk0011.jpg' },
    { code: 's1c5m3', name: 'Chemistry Set', villain: 'WRECKER', image: 'a/fs/c0011.jpg' },
    { code: 's1c5m4', name: 'Desecration', villain: 'ENCHANTRESS', image: 'a/fs/1tj0011.jpg' },
    { code: 's1c5m5', name: 'City of Stone', villain: 'LOKI', image: 'a/fs/2fg0011.jpg' },
    { code: 's1c5m6', name: 'Hydra Assemble!', villain: 'MILITANT', image: 'a/fs/vq0011.jpg' },
  ] },
  { chapter: 6, name: 'Uprising', missions: [
    { code: 's1c6m1', name: 'Underworld Masquerade', villain: 'MADAME MASQUE', image: 'a/fs/a60011.jpg' },
    { code: 's1c6m2', name: 'I Predict a Riot', villain: 'TOAD', image: 'a/fs/1no0011.jpg' },
    { code: 's1c6m3', name: 'Tentacular', villain: 'CRIMSON COWL', image: 'a/fs/2bq0011.jpg' },
    { code: 's1c6m4', name: 'Mutants Marching', villain: 'MYSTIQUE', image: 'a/fs/1on0012.jpg' },
    { code: 's1c6m5', name: 'Magic Hand', villain: 'ELEKTRA', image: 'a/fs/2m30011.jpg' },
    { code: 's1c6m6', name: 'Jailhouse Rock', villain: 'JUGGERNAUT', image: 'a/fs/3jt0011.jpg' },
  ] },
  { chapter: 7, name: 'M.I.A.', missions: [
    { code: 's1c7m1', name: 'Anticipation', villain: 'MOONSTONE', image: 'a/fs/2yi0011.jpg' },
    { code: 's1c7m2', name: 'Taking It to the Streets', villain: 'AVALANCHE', image: 'a/fs/1sc0011.jpg' },
    { code: 's1c7m3', name: 'Head Shot', villain: 'JACK O\'LANTERN', image: 'a/fs/30v0011.jpg' },
    { code: 's1c7m4', name: 'Deceiver and Destroyer', villain: 'DESTROYER', image: 'a/fs/xl0011.jpg' },
    { code: 's1c7m5', name: 'Chaos Reigns', villain: 'DORMAMMU', image: 'a/fs/1il0011.jpg' },
    { code: 's1c7m6', name: 'A Whole New U', villain: 'VECTOR', image: 'a/fs/34g0011.jpg' },
  ] },
  { chapter: 8, name: 'Dark Rites', missions: [
    { code: 's1c8m1', name: 'Dewey Decimation System', villain: 'SELENE SENTINEL', image: 'a/fs/3270011.jpg' },
    { code: 's1c8m2', name: 'Congressional Action', villain: 'TESLA NIMROD', image: 'a/fs/nm0011.jpg' },
    { code: 's1c8m3', name: 'Grand Experiment', villain: 'M-SERIES SIGMA MK IV', image: 'a/fs/at0011.jpg' },
    { code: 's1c8m4', name: 'Quis Custodiet', villain: 'OMEGA SENTINEL', image: 'a/fs/1gm0011.jpg' },
    { code: 's1c8m5', name: 'Regeneration', villain: 'VIPER', image: 'a/fs/3nq0011.jpg' },
    { code: 's1c8m6', name: 'Bring the Thunder', villain: 'DESTROYER', image: 'a/fs/3030011.jpg' },
  ] },
  { chapter: 9, name: 'The Syndicate', missions: [
    { code: 's1c9m1', name: 'The Boss Is Back', villain: 'FIXER', image: 'a/fs/3610011.jpg' },
    { code: 's1c9m2', name: 'Mutatis Mutandis', villain: 'CRIMSON COWL', image: 'a/fs/12h0011.jpg' },
    { code: 's1c9m3', name: 'Hand and Fist', villain: 'CONSTRICTOR', image: 'a/fs/7q0011.jpg' },
    { code: 's1c9m4', name: 'Weird Science', villain: 'ABOMINATION', image: 'a/fs/3il0011.jpg' },
    { code: 's1c9m5', name: 'Criminal Minds', villain: 'THE HOOD', image: 'a/fs/3870011.jpg' },
    { code: 's1c9m6', name: 'Darkness Rising', villain: 'DORMAMMU', image: 'a/fs/1su0011.jpg' },
  ] },
  { chapter: 10, name: 'Chaos Circle', missions: [
    { code: 's1c10m1', name: 'U-Foe Sighting', villain: 'IRONCLAD', image: 'a/fs/1wv0011.jpg' },
    { code: 's1c10m2', name: 'Power Play', villain: 'MADAME MASQUE', image: 'a/fs/27i0011.jpg' },
    { code: 's1c10m3', name: 'Stormy Weather', villain: 'HYDRO-MAN', image: 'a/fs/2ow0011.jpg' },
    { code: 's1c10m4', name: 'Grinning Skull', villain: 'ENCHANTRESS', image: 'a/fs/2jy0011.jpg' },
    { code: 's1c10m5', name: 'The Syndicate', villain: 'DR. DOOM', image: 'a/fs/3hf0011.jpg' },
    { code: 's1c10m6', name: 'Der Rote Schadel Lebt Noch', villain: 'ELEKTRA', image: 'a/fs/3h50011.jpg' },
  ] },
  { chapter: 11, name: 'Mutant Mayhem', missions: [
    { code: 's1c11m1', name: 'Mutants Take Manhattan', villain: 'JUGGERNAUT', image: 'a/fs/62e0008.jpg' },
    { code: 's1c11m2', name: 'HYDRA for Humans!', villain: 'TOAD', image: 'a/fs/62d0008.jpg' },
    { code: 's1c11m3', name: 'Enter the Circle', villain: 'MYSTIQUE', image: 'a/fs/62c0009.jpg' },
    { code: 's1c11m4', name: 'Underground Resistance', villain: 'BLOB', image: 'a/fs/62h0008.jpg' },
    { code: 's1c11m5', name: 'Mutation Zone', villain: 'MAGNETO', image: 'a/fs/62b0008.jpg' },
    { code: 's1c11m6', name: 'Breaking the Syndicate', villain: 'RED SKULL', image: 'a/fs/62f0008.jpg' },
  ] },
  { chapter: 12, name: 'Titanomachia', missions: [
    { code: 's1c12m1', name: 'Lokasenna', villain: 'LOKI', image: 'a/fs/6s40006.jpg' },
    { code: 's1c12m2', name: 'Ouroboros', villain: 'BARON ZEMO', image: 'a/fs/6s60006.jpg' },
    { code: 's1c12m3', name: 'Under the Hood', villain: 'DORMAMMU', image: 'a/fs/6s20006.jpg' },
    { code: 's1c12m4', name: 'Technocrats', villain: 'M.O.D.O.K.', image: 'a/fs/6s50006.jpg' },
    { code: 's1c12m5', name: 'Feeding Frenzy', villain: 'RED SKULL', image: 'a/fs/6s10006.jpg' },
    { code: 's1c12m6', name: 'Doom\'s Day', villain: 'DR. DOOM', image: 'a/fs/6s30006.jpg' },
  ] },
];

module.exports = { S1_CHAPTERS };
